# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
 title: Example Jekyll Blog
email: me@me.com
description: > # this means to ignore newlines until "baseurl:"
    Example blog 
baseurl: "/example-blog"  the subpath of your site, e.g. /blog
url: "http://you.github.io/" # the base hostname & protocol for your site
twitter_username: mytwitter
github_username: github_username

# Build settings
markdown: kramdown
highlighter: rouge
